# 利用实现接口的方式设置了端口
#server:
#  port: 7071
  
eureka:
  client:
    register-with-eureka: true
    fetch-registry: false
    serviceUrl: 
      defaultZone: http://localhost:7070/eureka/

spring:
  application:
    name: userService
  jpa:
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: none
  datasource:
    url: 
    platform: h2
    schema:
    - classpath:sql/schema.sql
    data:
    - classpath:sql/data.sql
logging:
  level:
    root: INFO
    org.hibernate.Hibernate: INFO
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.hibernate.type.descriptor.sql.BasicExtractcr: TRACE
    com.boot.demo: DEBUG
  
    
    
    